#pragma once

#include "utils.h"
  
#define CURRENT_STORAGE_VERSION 4

#define PERSIST_SLEEP       231
#define PERSIST_WALK        233
#define PERSIST_JOG         234
#define PERSIST_STEPS       236
#define PERSIST_WKD         238
#define PERSIST_WKE         240


#define PERSIST_AVG_SLEEP        131
#define PERSIST_AVG_WALK         133
#define PERSIST_AVG_JOG          134
#define PERSIST_AVG_STEPS        136

#define PERSIST_YEST_SLEEP        191
#define PERSIST_YEST_WALK         193
#define PERSIST_YEST_JOG          194
#define PERSIST_YEST_STEPS        196

#define PERSIST_STEPS_DAY0        60
#define PERSIST_WALK_DAY0        70
#define PERSIST_RUN_DAY0        80
#define PERSIST_SLEEP_DAY0        90

#define PERSIST_IDLE_TIME            142
#define PERSIST_RESET_TIMESTAMP      143
#define PERSIST_DATALOGGING_ACTIVATION    144
#define PERSIST_PAUSE_TIME           145
#define PERSIST_COMM_ACTIVATION      146
#define PERSIST_ACTIVE_TRACK         147
#define PERSIST_ACTIVE_TRACK_PAUSE   148
#define PERSIST_ACTIVE_TRACK_TYPE    149
#define PERSIST_ACTIVE_TRACK_START   150
#define PERSIST_ACTIVE_TRACK_GPS_BLE 153
#define PERSIST_ACTIVE_TRACK_DURATION 152
#define PERSIST_DISPLAY_DATA_PHONE   154

#define PERSIST_WORKER_WAKEUP_MESSAGE    160

#define PERSIST_STORAGE_VERSION      280

#define PERSIST_ALARM0 320
#define PERSIST_ALARM1 321
#define PERSIST_ALARM2 322
#define PERSIST_ALARM3 323
#define PERSIST_ALARM4 324
#define PERSIST_ALARM5 325
#define PERSIST_ALARM6 326
#define PERSIST_SNOOZE_ALARM 327
#define PERSIST_SINGLE_ALARM 328
#define PERSIST_AUTO_SNOOZE  329

#define PERSIST_ALARM_TIME0 270
#define PERSIST_ALARM_TIME1 271
#define PERSIST_ALARM_TIME2 272
#define PERSIST_ALARM_TIME3 273
#define PERSIST_ALARM_TIME4 274
#define PERSIST_ALARM_TIME5 275
#define PERSIST_ALARM_TIME6 276
#define PERSIST_SINGLE_ALARM_TIME 278
  
  void manage_persist();
